use tauri::{generate_handler, Invoke};

mod db;
mod files;
mod settings;

pub fn handler() -> impl Fn(Invoke) {
    generate_handler![
        db::ensembles::ensembles_get_all,
        db::ensembles::ensembles_get_by_id,
        db::ensembles::ensembles_add,
        db::ensembles::ensembles_update,
        db::ensembles::ensembles_delete,
        db::ensembles::ensembles_add_instrument,
        db::instruments::instruments_get_all,
        db::instruments::instruments_get_id,
        db::instruments::instruments_add,
        db::instruments::instruments_update,
        db::instruments::instruments_delete,
        db::musicians::musicians_get_all,
        db::musicians::musicians_get_by_id,
        db::musicians::musicians_add,
        db::musicians::musicians_update,
        db::musicians::musicians_delete,
        db::parts::parts_get_all,
        db::parts::parts_get_by_id,
        db::parts::parts_add,
        db::parts::parts_update,
        db::parts::parts_delete,
        db::parts::parts_set_instruments,
        db::pieces::pieces_get_all,
        db::pieces::pieces_get_by_setlist,
        db::pieces::pieces_get_by_id,
        db::pieces::pieces_add,
        db::pieces::pieces_update,
        db::pieces::pieces_delete,
        db::pieces::pieces_set_musicians,
        db::pieces::pieces_set_tags,
        db::scores::scores_get_all,
        db::scores::scores_get_by_id,
        db::scores::scores_add,
        db::scores::scores_update,
        db::scores::scores_delete,
        db::setlists::setlists_get_all,
        db::setlists::setlists_get_by_id,
        db::setlists::setlists_add,
        db::setlists::setlists_update,
        db::setlists::setlists_delete,
        db::tags::tags_get_all,
        db::tags::tags_get_by_id,
        db::tags::tags_add,
        db::tags::tags_update,
        db::tags::tags_delete,
        files::open_dir,
        files::delete_dir,
        settings::get_working_directory,
        settings::get_open_on_startup,
        settings::set_working_directory,
        settings::set_open_on_startup,
    ]
}
