//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ensembles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub category: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ensembles_parts::Entity")]
    EnsemblesParts,
}

impl Related<super::ensembles_parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnsemblesParts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
