//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ensembles_parts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ensemble_id: i32,
    pub name: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ensemble_parts_instruments::Entity")]
    EnsemblePartsInstruments,
    #[sea_orm(
        belongs_to = "super::ensembles::Entity",
        from = "Column::EnsembleId",
        to = "super::ensembles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Ensembles,
}

impl Related<super::ensemble_parts_instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnsemblePartsInstruments.def()
    }
}

impl Related<super::ensembles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ensembles.def()
    }
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        super::ensemble_parts_instruments::Relation::Instruments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::ensemble_parts_instruments::Relation::EnsemblesParts
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
