//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ensemble_parts_instruments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub part_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub instrument_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ensembles_parts::Entity",
        from = "Column::PartId",
        to = "super::ensembles_parts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EnsemblesParts,
    #[sea_orm(
        belongs_to = "super::instruments::Entity",
        from = "Column::InstrumentId",
        to = "super::instruments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instruments,
}

impl Related<super::ensembles_parts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EnsemblesParts.def()
    }
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instruments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
