//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ensembles_instruments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ensemble_id: i32,
    pub instrument_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ensembles::Entity",
        from = "Column::EnsembleId",
        to = "super::ensembles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Ensembles,
    #[sea_orm(
        belongs_to = "super::instruments::Entity",
        from = "Column::InstrumentId",
        to = "super::instruments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Instruments,
}

impl Related<super::ensembles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ensembles.def()
    }
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instruments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
