//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod ensemble_parts_instruments;
pub mod ensembles;
pub mod ensembles_parts;
pub mod instruments;
pub mod musicians;
pub mod parts;
pub mod parts_instruments;
pub mod pieces;
pub mod pieces_musicians;
pub mod pieces_setlists;
pub mod pieces_tags;
pub mod scores;
pub mod setlists;
pub mod tags;
