//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "musicians")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_name: String,
    pub last_name: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pieces_musicians::Entity")]
    PiecesMusicians,
}

impl Related<super::pieces_musicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PiecesMusicians.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
