//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "parts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub path: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub piece_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::parts_instruments::Entity")]
    PartsInstruments,
    #[sea_orm(
        belongs_to = "super::pieces::Entity",
        from = "Column::PieceId",
        to = "super::pieces::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Pieces,
}

impl Related<super::parts_instruments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartsInstruments.def()
    }
}

impl Related<super::pieces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pieces.def()
    }
}

impl Related<super::instruments::Entity> for Entity {
    fn to() -> RelationDef {
        super::parts_instruments::Relation::Instruments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::parts_instruments::Relation::Parts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
