//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::ensemble_parts_instruments::Entity as EnsemblePartsInstruments;
pub use super::ensembles::Entity as Ensembles;
pub use super::ensembles_parts::Entity as EnsemblesParts;
pub use super::instruments::Entity as Instruments;
pub use super::musicians::Entity as Musicians;
pub use super::parts::Entity as Parts;
pub use super::parts_instruments::Entity as PartsInstruments;
pub use super::pieces::Entity as Pieces;
pub use super::pieces_musicians::Entity as PiecesMusicians;
pub use super::pieces_setlists::Entity as PiecesSetlists;
pub use super::pieces_tags::Entity as PiecesTags;
pub use super::scores::Entity as Scores;
pub use super::setlists::Entity as Setlists;
pub use super::tags::Entity as Tags;
